### PR TITLE
fix formatting of vasp2cif file

### PR DESCRIPTION
**Pull request by ltalirz**
Start addressing #16

### CODE REVIEW

**Comment by ltalirz** [comment]
@torbjornbjorkman I've fixed the tabs/spaces issue in the `vasp2cif` file, but one still cannot use it:

```
$ ./vasp2cif
Traceback (most recent call last):
  File "./vasp2cif", line 54, in <module>
    import commands
ModuleNotFoundError: No module named 'commands'
```

It seems it expects a mysterious `commands` module that is not part of the codebase at all... has it not been committed?

By the way, this issue also calls for a continuous integration test of `vasp2cif`. Can you provide an example input/output?

**Comment by merkys** [comment]
> It seems it expects a mysterious `commands` module that is not part of the codebase at all... has it not been committed?

@ltalirz I think this is a leftover library import from Python 2. According to [Python 2 docs](https://docs.python.org/2/library/commands.html), it has been replaced by `subprocess`.

**Comment by ltalirz** [comment]
@merkys ah, thanks! I've somehow managed to never come across this before ;-)

**Comment by ltalirz** [comment]
@torbjornbjorkman Are you still monitoring this repository?
Should I just go ahead and merge changes like these or do you wish to review pull requests?

**Pull request merged**
